2021-10-26 19:12:23.068 | INFO     |  5431 | __main__:main:46 | Starting Audio Service
2021-10-26 19:12:23.069 | INFO     |  5431 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2021-10-26 19:12:23.073 | INFO     |  5431 | mycroft_bus_client.client.client | Connected
2021-10-26 19:12:23.075 | INFO     |  5431 | mycroft.util.process_utils:start_message_bus_client:155 | Connected to messagebus
2021-10-26 19:12:23.078 | WARNING  |  5431 | mycroft.tts.tts:clear_cache:428 | This method is deprecated, use TextToSpeechCache.clear
2021-10-26 19:12:23.318 | ERROR    |  5431 | mycroft.tts.mimic_tts:validate_connection:226 | Mimic executable not found
2021-10-26 19:12:23.318 | ERROR    |  5431 | mycroft.tts.tts:create:625 | The TTS could not be loaded.
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 221, in validate_connection
    subprocess.call([mimic_bin, '--version'])
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 1465, in _execute_child
    executable = os.fsencode(executable)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/os.py", line 812, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 614, in create
    tts.validator.validate()
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 500, in validate
    self.validate_connection()
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 229, in validate_connection
    from err
Exception: Mimic was not found. Run install-mimic.sh to install it.
2021-10-26 19:12:23.336 | ERROR    |  5431 | __main__:on_error:37 | Audio service failed to launch (Exception('Mimic was not found. Run install-mimic.sh to install it.')).
2021-10-26 19:12:38.035 | ERROR    |  5431 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:08.540 | ERROR    |  5431 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:08.541 | ERROR    |  5431 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:38.875 | ERROR    |  5431 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:38.875 | ERROR    |  5431 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:38.876 | ERROR    |  5431 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:38.876 | ERROR    |  5431 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:38.876 | ERROR    |  5431 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:38.877 | ERROR    |  5431 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:38.877 | ERROR    |  5431 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:39.094 | ERROR    |  5431 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb29aaf2550>>: cannot schedule new futures after shutdown
2021-10-26 19:13:43.110 | INFO     |  7048 | __main__:main:46 | Starting Audio Service
2021-10-26 19:13:43.111 | INFO     |  7048 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2021-10-26 19:13:43.115 | INFO     |  7048 | mycroft_bus_client.client.client | Connected
2021-10-26 19:13:43.115 | INFO     |  7048 | mycroft.util.process_utils:start_message_bus_client:155 | Connected to messagebus
2021-10-26 19:13:43.119 | WARNING  |  7048 | mycroft.tts.tts:clear_cache:428 | This method is deprecated, use TextToSpeechCache.clear
2021-10-26 19:13:43.185 | ERROR    |  7048 | mycroft.tts.mimic_tts:validate_connection:226 | Mimic executable not found
2021-10-26 19:13:43.186 | ERROR    |  7048 | mycroft.tts.tts:create:625 | The TTS could not be loaded.
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 221, in validate_connection
    subprocess.call([mimic_bin, '--version'])
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 1465, in _execute_child
    executable = os.fsencode(executable)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/os.py", line 812, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 614, in create
    tts.validator.validate()
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 500, in validate
    self.validate_connection()
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 229, in validate_connection
    from err
Exception: Mimic was not found. Run install-mimic.sh to install it.
2021-10-26 19:13:43.188 | ERROR    |  7048 | __main__:on_error:37 | Audio service failed to launch (Exception('Mimic was not found. Run install-mimic.sh to install it.')).
2021-10-26 19:13:44.781 | ERROR    |  7048 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:45.169 | ERROR    |  7048 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:45.512 | ERROR    |  7048 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:45.853 | ERROR    |  7048 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:46.528 | ERROR    |  7048 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:48.951 | ERROR    |  7048 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:54.835 | ERROR    |  7048 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:55.233 | ERROR    |  7048 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:55.881 | ERROR    |  7048 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:56.313 | ERROR    |  7048 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:56.920 | ERROR    |  7048 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:57.938 | ERROR    |  7048 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:13:59.309 | ERROR    |  7048 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 19:14:05.187 | ERROR    |  7048 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
Exception ignored in: <module 'threading' from '/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
KeyboardInterrupt
