2021-10-26 14:39:34.766 | INFO     |  5815 | __main__:main:46 | Starting Audio Service
2021-10-26 14:39:34.767 | INFO     |  5815 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2021-10-26 14:39:34.771 | INFO     |  5815 | mycroft_bus_client.client.client | Connected
2021-10-26 14:39:34.772 | INFO     |  5815 | mycroft.util.process_utils:start_message_bus_client:155 | Connected to messagebus
2021-10-26 14:39:34.781 | WARNING  |  5815 | mycroft.tts.tts:clear_cache:428 | This method is deprecated, use TextToSpeechCache.clear
2021-10-26 14:39:34.978 | ERROR    |  5815 | mycroft.tts.mimic_tts:validate_connection:226 | Mimic executable not found
2021-10-26 14:39:34.978 | ERROR    |  5815 | mycroft.tts.tts:create:625 | The TTS could not be loaded.
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 221, in validate_connection
    subprocess.call([mimic_bin, '--version'])
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 1465, in _execute_child
    executable = os.fsencode(executable)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/os.py", line 812, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 614, in create
    tts.validator.validate()
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 500, in validate
    self.validate_connection()
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 229, in validate_connection
    from err
Exception: Mimic was not found. Run install-mimic.sh to install it.
2021-10-26 14:39:34.996 | ERROR    |  5815 | __main__:on_error:37 | Audio service failed to launch (Exception('Mimic was not found. Run install-mimic.sh to install it.')).
2021-10-26 14:39:47.640 | ERROR    |  5815 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:40:18.190 | ERROR    |  5815 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:40:18.190 | ERROR    |  5815 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:40:48.541 | ERROR    |  5815 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:40:48.542 | ERROR    |  5815 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:40:48.543 | ERROR    |  5815 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:40:48.543 | ERROR    |  5815 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:40:48.560 | ERROR    |  5815 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:40:48.561 | ERROR    |  5815 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:40:48.561 | ERROR    |  5815 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:41:09.907 | INFO     |  7453 | __main__:main:46 | Starting Audio Service
2021-10-26 14:41:09.908 | INFO     |  7453 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2021-10-26 14:41:09.912 | INFO     |  7453 | mycroft_bus_client.client.client | Connected
2021-10-26 14:41:09.913 | INFO     |  7453 | mycroft.util.process_utils:start_message_bus_client:155 | Connected to messagebus
2021-10-26 14:41:09.917 | WARNING  |  7453 | mycroft.tts.tts:clear_cache:428 | This method is deprecated, use TextToSpeechCache.clear
2021-10-26 14:41:10.004 | ERROR    |  7453 | mycroft.tts.mimic_tts:validate_connection:226 | Mimic executable not found
2021-10-26 14:41:10.005 | ERROR    |  7453 | mycroft.tts.tts:create:625 | The TTS could not be loaded.
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 221, in validate_connection
    subprocess.call([mimic_bin, '--version'])
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 1465, in _execute_child
    executable = os.fsencode(executable)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/os.py", line 812, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 614, in create
    tts.validator.validate()
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 500, in validate
    self.validate_connection()
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 229, in validate_connection
    from err
Exception: Mimic was not found. Run install-mimic.sh to install it.
2021-10-26 14:41:10.006 | ERROR    |  7453 | __main__:on_error:37 | Audio service failed to launch (Exception('Mimic was not found. Run install-mimic.sh to install it.')).
2021-10-26 14:41:11.848 | ERROR    |  7453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:41:12.248 | ERROR    |  7453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:41:12.650 | ERROR    |  7453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:41:13.050 | ERROR    |  7453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:41:14.068 | ERROR    |  7453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:41:22.255 | ERROR    |  7453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:41:22.700 | ERROR    |  7453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:41:23.076 | ERROR    |  7453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:41:23.422 | ERROR    |  7453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:41:24.091 | ERROR    |  7453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:41:24.461 | ERROR    |  7453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:41:25.492 | ERROR    |  7453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:41:31.933 | ERROR    |  7453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 14:41:32.786 | ERROR    |  7453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
Exception ignored in: <module 'threading' from '/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
KeyboardInterrupt
