2021-10-27 06:10:29.181 | INFO     |  5453 | __main__:main:46 | Starting Audio Service
2021-10-27 06:10:29.182 | INFO     |  5453 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2021-10-27 06:10:29.189 | INFO     |  5453 | mycroft_bus_client.client.client | Connected
2021-10-27 06:10:29.190 | INFO     |  5453 | mycroft.util.process_utils:start_message_bus_client:155 | Connected to messagebus
2021-10-27 06:10:29.194 | WARNING  |  5453 | mycroft.tts.tts:clear_cache:428 | This method is deprecated, use TextToSpeechCache.clear
2021-10-27 06:10:29.695 | ERROR    |  5453 | mycroft.tts.mimic_tts:validate_connection:226 | Mimic executable not found
2021-10-27 06:10:29.695 | ERROR    |  5453 | mycroft.tts.tts:create:625 | The TTS could not be loaded.
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 221, in validate_connection
    subprocess.call([mimic_bin, '--version'])
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 1465, in _execute_child
    executable = os.fsencode(executable)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/os.py", line 812, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 614, in create
    tts.validator.validate()
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 500, in validate
    self.validate_connection()
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 229, in validate_connection
    from err
Exception: Mimic was not found. Run install-mimic.sh to install it.
2021-10-27 06:10:29.733 | ERROR    |  5453 | __main__:on_error:37 | Audio service failed to launch (Exception('Mimic was not found. Run install-mimic.sh to install it.')).
2021-10-27 06:10:40.374 | ERROR    |  5453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:11:11.235 | ERROR    |  5453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:11:11.236 | ERROR    |  5453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:11:41.559 | ERROR    |  5453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:11:41.560 | ERROR    |  5453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:11:41.560 | ERROR    |  5453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:11:41.561 | ERROR    |  5453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:11:41.561 | ERROR    |  5453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:11:41.562 | ERROR    |  5453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:11:41.562 | ERROR    |  5453 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:11:53.207 | ERROR    |  5453 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f4b9f553f10>>: cannot schedule new futures after interpreter shutdown
2021-10-27 06:11:53.207 | ERROR    |  5453 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f4b9f553f10>>: cannot schedule new futures after interpreter shutdown
2021-10-27 06:11:53.207 | ERROR    |  5453 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f4b9f553f10>>: cannot schedule new futures after interpreter shutdown
2021-10-27 06:11:53.208 | ERROR    |  5453 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f4b9f553f10>>: cannot schedule new futures after interpreter shutdown
2021-10-27 06:11:53.208 | ERROR    |  5453 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f4b9f553f10>>: cannot schedule new futures after interpreter shutdown
2021-10-27 06:11:57.096 | INFO     |  7089 | __main__:main:46 | Starting Audio Service
2021-10-27 06:11:57.098 | INFO     |  7089 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2021-10-27 06:11:57.102 | INFO     |  7089 | mycroft_bus_client.client.client | Connected
2021-10-27 06:11:57.112 | INFO     |  7089 | mycroft.util.process_utils:start_message_bus_client:155 | Connected to messagebus
2021-10-27 06:11:57.123 | WARNING  |  7089 | mycroft.tts.tts:clear_cache:428 | This method is deprecated, use TextToSpeechCache.clear
2021-10-27 06:11:57.749 | ERROR    |  7089 | mycroft.tts.mimic_tts:validate_connection:226 | Mimic executable not found
2021-10-27 06:11:57.749 | ERROR    |  7089 | mycroft.tts.tts:create:625 | The TTS could not be loaded.
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 221, in validate_connection
    subprocess.call([mimic_bin, '--version'])
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 1465, in _execute_child
    executable = os.fsencode(executable)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/os.py", line 812, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 614, in create
    tts.validator.validate()
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 500, in validate
    self.validate_connection()
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 229, in validate_connection
    from err
Exception: Mimic was not found. Run install-mimic.sh to install it.
2021-10-27 06:11:57.751 | ERROR    |  7089 | __main__:on_error:37 | Audio service failed to launch (Exception('Mimic was not found. Run install-mimic.sh to install it.')).
2021-10-27 06:11:59.410 | ERROR    |  7089 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:11:59.802 | ERROR    |  7089 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:12:00.153 | ERROR    |  7089 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:12:00.541 | ERROR    |  7089 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:12:01.559 | ERROR    |  7089 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:12:09.813 | ERROR    |  7089 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:12:10.176 | ERROR    |  7089 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:12:10.560 | ERROR    |  7089 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:12:10.909 | ERROR    |  7089 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:12:11.578 | ERROR    |  7089 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:12:11.942 | ERROR    |  7089 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:12:19.450 | ERROR    |  7089 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:12:20.259 | ERROR    |  7089 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-27 06:12:20.841 | ERROR    |  7089 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
Exception ignored in: <module 'threading' from '/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
KeyboardInterrupt
