2021-10-25 08:04:24.242 | INFO     |  5687 | __main__:main:46 | Starting Audio Service
2021-10-25 08:04:24.243 | INFO     |  5687 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2021-10-25 08:04:24.246 | INFO     |  5687 | mycroft_bus_client.client.client | Connected
2021-10-25 08:04:24.247 | INFO     |  5687 | mycroft.util.process_utils:start_message_bus_client:155 | Connected to messagebus
2021-10-25 08:04:24.251 | WARNING  |  5687 | mycroft.tts.tts:clear_cache:428 | This method is deprecated, use TextToSpeechCache.clear
2021-10-25 08:04:24.413 | ERROR    |  5687 | mycroft.tts.mimic_tts:validate_connection:226 | Mimic executable not found
2021-10-25 08:04:24.413 | ERROR    |  5687 | mycroft.tts.tts:create:625 | The TTS could not be loaded.
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 221, in validate_connection
    subprocess.call([mimic_bin, '--version'])
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 1465, in _execute_child
    executable = os.fsencode(executable)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/os.py", line 812, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 614, in create
    tts.validator.validate()
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 500, in validate
    self.validate_connection()
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 229, in validate_connection
    from err
Exception: Mimic was not found. Run install-mimic.sh to install it.
2021-10-25 08:04:24.431 | ERROR    |  5687 | __main__:on_error:37 | Audio service failed to launch (Exception('Mimic was not found. Run install-mimic.sh to install it.')).
2021-10-25 08:04:37.143 | ERROR    |  5687 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-25 08:05:07.683 | ERROR    |  5687 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-25 08:05:07.684 | ERROR    |  5687 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-25 08:05:22.260 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.260 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.260 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.261 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.261 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.261 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.261 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.261 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.262 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.262 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.262 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.262 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.263 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.263 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.263 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.263 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.263 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.264 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.264 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.264 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.264 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.264 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:22.265 | ERROR    |  5687 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f76dbb7ff10>>: cannot schedule new futures after interpreter shutdown
2021-10-25 08:05:39.429 | INFO     |  7295 | __main__:main:46 | Starting Audio Service
2021-10-25 08:05:39.430 | INFO     |  7295 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2021-10-25 08:05:39.432 | INFO     |  7295 | mycroft_bus_client.client.client | Connected
2021-10-25 08:05:39.434 | INFO     |  7295 | mycroft.util.process_utils:start_message_bus_client:155 | Connected to messagebus
2021-10-25 08:05:39.437 | WARNING  |  7295 | mycroft.tts.tts:clear_cache:428 | This method is deprecated, use TextToSpeechCache.clear
2021-10-25 08:05:39.593 | ERROR    |  7295 | mycroft.tts.mimic_tts:validate_connection:226 | Mimic executable not found
2021-10-25 08:05:39.593 | ERROR    |  7295 | mycroft.tts.tts:create:625 | The TTS could not be loaded.
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 221, in validate_connection
    subprocess.call([mimic_bin, '--version'])
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 1465, in _execute_child
    executable = os.fsencode(executable)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/os.py", line 812, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 614, in create
    tts.validator.validate()
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 500, in validate
    self.validate_connection()
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 229, in validate_connection
    from err
Exception: Mimic was not found. Run install-mimic.sh to install it.
2021-10-25 08:05:39.595 | ERROR    |  7295 | __main__:on_error:37 | Audio service failed to launch (Exception('Mimic was not found. Run install-mimic.sh to install it.')).
2021-10-25 08:07:29.417 | ERROR    |  7295 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-25 08:07:29.417 | ERROR    |  7295 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-25 08:07:29.418 | ERROR    |  7295 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-25 08:07:29.418 | ERROR    |  7295 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-25 08:07:29.418 | ERROR    |  7295 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-25 08:07:29.419 | ERROR    |  7295 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-25 08:07:29.419 | ERROR    |  7295 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
Exception ignored in: <module 'threading' from '/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
KeyboardInterrupt
