2021-10-23 07:46:46.188 | INFO     |  5785 | __main__:main:46 | Starting Audio Service
2021-10-23 07:46:46.188 | INFO     |  5785 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2021-10-23 07:46:46.205 | INFO     |  5785 | mycroft_bus_client.client.client | Connected
2021-10-23 07:46:46.211 | INFO     |  5785 | mycroft.util.process_utils:start_message_bus_client:155 | Connected to messagebus
2021-10-23 07:46:46.218 | WARNING  |  5785 | mycroft.tts.tts:clear_cache:428 | This method is deprecated, use TextToSpeechCache.clear
2021-10-23 07:46:46.470 | ERROR    |  5785 | mycroft.tts.mimic_tts:validate_connection:226 | Mimic executable not found
2021-10-23 07:46:46.470 | ERROR    |  5785 | mycroft.tts.tts:create:625 | The TTS could not be loaded.
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 221, in validate_connection
    subprocess.call([mimic_bin, '--version'])
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 1465, in _execute_child
    executable = os.fsencode(executable)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/os.py", line 812, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 614, in create
    tts.validator.validate()
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 500, in validate
    self.validate_connection()
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 229, in validate_connection
    from err
Exception: Mimic was not found. Run install-mimic.sh to install it.
2021-10-23 07:46:46.487 | ERROR    |  5785 | __main__:on_error:37 | Audio service failed to launch (Exception('Mimic was not found. Run install-mimic.sh to install it.')).
2021-10-23 07:47:00.063 | ERROR    |  5785 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:47:30.584 | ERROR    |  5785 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:47:30.584 | ERROR    |  5785 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:47:42.234 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.234 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.234 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.235 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.235 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.235 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.235 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.235 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.235 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.236 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.236 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.236 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.236 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.236 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.236 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.237 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.241 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.241 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.241 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.242 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.242 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.242 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.242 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.242 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.242 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.243 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.243 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.243 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.243 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.243 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.243 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.244 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.244 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.244 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.244 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.244 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.244 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.245 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.245 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after interpreter shutdown
2021-10-23 07:47:42.259 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after shutdown
2021-10-23 07:47:42.259 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after shutdown
2021-10-23 07:47:42.259 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after shutdown
2021-10-23 07:47:42.259 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after shutdown
2021-10-23 07:47:42.260 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after shutdown
2021-10-23 07:47:42.260 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after shutdown
2021-10-23 07:47:42.260 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after shutdown
2021-10-23 07:47:42.260 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after shutdown
2021-10-23 07:47:42.260 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after shutdown
2021-10-23 07:47:42.260 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after shutdown
2021-10-23 07:47:42.261 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after shutdown
2021-10-23 07:47:42.261 | ERROR    |  5785 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fb261ac0c50>>: cannot schedule new futures after shutdown
2021-10-23 07:47:54.442 | INFO     |  7380 | __main__:main:46 | Starting Audio Service
2021-10-23 07:47:54.443 | INFO     |  7380 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2021-10-23 07:47:54.445 | INFO     |  7380 | mycroft_bus_client.client.client | Connected
2021-10-23 07:47:54.447 | INFO     |  7380 | mycroft.util.process_utils:start_message_bus_client:155 | Connected to messagebus
2021-10-23 07:47:54.449 | WARNING  |  7380 | mycroft.tts.tts:clear_cache:428 | This method is deprecated, use TextToSpeechCache.clear
2021-10-23 07:47:54.627 | ERROR    |  7380 | mycroft.tts.mimic_tts:validate_connection:226 | Mimic executable not found
2021-10-23 07:47:54.628 | ERROR    |  7380 | mycroft.tts.tts:create:625 | The TTS could not be loaded.
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 221, in validate_connection
    subprocess.call([mimic_bin, '--version'])
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 1465, in _execute_child
    executable = os.fsencode(executable)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/os.py", line 812, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 614, in create
    tts.validator.validate()
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 500, in validate
    self.validate_connection()
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 229, in validate_connection
    from err
Exception: Mimic was not found. Run install-mimic.sh to install it.
2021-10-23 07:47:54.629 | ERROR    |  7380 | __main__:on_error:37 | Audio service failed to launch (Exception('Mimic was not found. Run install-mimic.sh to install it.')).
2021-10-23 07:47:57.105 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:47:57.447 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:47:57.833 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:47:58.470 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:48:03.910 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:48:03.910 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:48:03.911 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:48:03.911 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:48:03.911 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:48:03.912 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:48:03.912 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:48:04.921 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:48:07.480 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:48:07.876 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:48:08.517 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:48:08.908 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:48:09.924 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:48:14.264 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:48:17.492 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:48:18.223 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-23 07:48:18.817 | ERROR    |  7380 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
Exception ignored in: <module 'threading' from '/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
KeyboardInterrupt
